# Generated by Django 5.2 on 2025-10-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_delivery_type_remove_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
