# Generated by Django 5.2 on 2025-09-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_min_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='article',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
    ]
